# Generated by Django 3.0.7 on 2021-02-27 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_ID', models.IntegerField(default=' ', max_length=10, primary_key=True, serialize=False)),
                ('teacher_lastname', models.CharField(default='', max_length=50, null=True)),
                ('teacher_firstname', models.CharField(default='', max_length=50, null=True)),
                ('teaching_grade', models.CharField(default='', max_length=50, null=True)),
                ('teacher_street_address', models.CharField(default='', max_length=100, null=True)),
                ('teacher_city', models.CharField(default='', max_length=50, null=True)),
                ('teacher_state', models.CharField(default='', max_length=50, null=True)),
                ('teacher_zip', models.CharField(blank=True, default='00000', max_length=50, null=True)),
                ('teacher_email', models.EmailField(default=' ', max_length=100)),
                ('teacher_phone', models.CharField(default='(402)000-0000', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_ID', models.IntegerField(default=' ', max_length=10, primary_key=True, serialize=False)),
                ('student_lastname', models.CharField(default='', max_length=50, null=True)),
                ('student_firstname', models.CharField(default='', max_length=50, null=True)),
                ('student_grade', models.CharField(default='', max_length=50, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teacher', to='Schools.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_ID', models.IntegerField(default=' ', max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='Schools.Student')),
            ],
        ),
    ]
