# Generated by Django 3.0.7 on 2021-02-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_name',
            new_name='teacher_firstname',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_email',
            field=models.EmailField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_lastname',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_phone',
            field=models.CharField(default='(402)000-0000', max_length=50),
        ),
    ]
