# Generated by Django 3.0.7 on 2021-02-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0002_auto_20210201_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_school_ID',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='school_ID',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.AddField(
            model_name='attendance',
            name='Attendance_student_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='Schools.Student'),
        ),
    ]
