# Generated by Django 3.0.7 on 2021-02-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0002_auto_20210227_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
